
# This is a free tier Supabase configuration file
# It is used by Supabase CLI to configure your local development environment
# Learn more about configuration here: https://supabase.com/docs/reference/cli/config

project_id = "hhxwwozpvgktuqutfkhc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[edge_runtime]
enabled = true

[[functions]]
name = "mobile-money"
verify_jwt = false

[[functions]]
name = "btc-payment"
verify_jwt = false
