// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhxwwozpvgktuqutfkhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeHd3b3pwdmdrdHVxdXRma2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0Mjk3NzYsImV4cCI6MjA1NzAwNTc3Nn0.7CcqhDwihx-e71VXSn11cZrYqPj-wZHiR85Ew1GniNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);