
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhxwwozpvgktuqutfkhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeHd3b3pwdmdrdHVxdXRma2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0Mjk3NzYsImV4cCI6MjA1NzAwNTc3Nn0.7CcqhDwihx-e71VXSn11cZrYqPj-wZHiR85Ew1GniNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper type for working with the metadata column
export type KycMetadata = {
  rejection_reason?: string;
  [key: string]: any;
};

// Helper type for virtual card data
export interface VirtualCard {
  id: string;
  user_id: string;
  name: string;
  number: string;
  masked_number: string;
  cvv: string;
  expiry: string;
  balance: number;
  status: 'active' | 'frozen' | 'cancelled';
  provider: string;
  card_type: string;
  created_at: string;
  updated_at: string;
  currency: string;
  limits?: {
    daily?: number;
    monthly?: number;
    transaction?: number;
  };
  settings?: {
    online_transactions: boolean;
    international_transactions: boolean;
  };
}

// Helper type for transaction filters moved to src/types/transaction.ts
